// src/counter/presentation/lit/App.ts
import {html, css, LitElement} from "lit";
import {customElement} from "lit/decorators.js";

import './CounterCard.ts';

@customElement("lit-app")
export class LitApp extends LitElement {

  static styles = css`
    div {
      padding: 1rem;
      border: 1px solid black;
    }
  `;

  render() {
    return html`<div>
      <h1>Lit</h1>
      <counter-card></counter-card>
      <counter-card></counter-card>
    </div>`;
  }
}

// src/counter/presentation/svelte/App.svelte
<script lang="ts">
  import CounterCard from "./CounterCard.svelte";

  let test = "test";
</script>

<div class="svelte-component">
  <h1>Svelte</h1>
  <div class="counter-list">
    <CounterCard/>
    <CounterCard/>
  </div>
</div>

<style>
.svelte-component {
  padding: 1rem;
  border: 1px solid black;
}
</style>
