// src/counter/presentation/react/CounterCard.tsx
import { useEffect, useReducer } from 'react';
import { presenter, service } from '../../configuration';

const useCounter = ()  => {
  const [counter, dispatch] = useReducer((_,newValue) => newValue, { counterValue: 0 });

  useEffect(() => {
    presenter.addCallback(dispatch);
    service.getCounterValue();
    return () => presenter.removeCallback(dispatch);
  }, []);

  return {
    counter,
    addToCounter: () => service.updateCounter(1)
  };
}

export const CounterCard = () => {
  const {counter, addToCounter} = useCounter();

  return <div style={{display: "flex", gap: "1rem", marginBottom: "1rem"}}>
    <div>{counter.counterValue}</div>
    <button onClick={addToCounter}>click</button>
  </div>
}

// src/counter/presentation/vue/CounterCard.vue
<script setup>
  import { ref, onMounted, onBeforeUnmount } from "vue";
  import { presenter, service } from '../../configuration';

  const count = ref({counterValue: 0});
  const dispatch = (newValue) => count.value = newValue;
  const addToCounter = () => service.updateCounter(1);

  onMounted(() => {
    presenter.addCallback(dispatch);
    service.getCounterValue();
  });

  onBeforeUnmount(() => {
    presenter.removeCallback(dispatch);
  })
</script>

<template>
  <div class="vue-counter">
    <div>{{ count.counterValue }}</div>
    <button @click="addToCounter">click</button>
  </div>
</template>

<style scoped>
.vue-counter {
  display: flex;
  gap: 1rem;
  margin-bottom: 1rem;
}
</style>
